development:
  adapter: postgresql
  encoding: unicode
  database: coin_profit
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: coin_profit_test
  pool: 5
  host: localhost
